version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: stock_tracking_db
    environment:
      POSTGRES_DB: stock_tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock_tracking_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_tracking_backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: stock_tracking
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - stock_tracking_network
    volumes:
      - ./backend/.env:/app/.env

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_tracking_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - stock_tracking_network

networks:
  stock_tracking_network:
    driver: bridge

volumes:
  postgres_data: